// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ds_out //
// ------ //

#define ds_out_wrap_target 0
#define ds_out_wrap 1

static const uint16_t ds_out_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1                    
    0x0000, //  1: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ds_out_program = {
    .instructions = ds_out_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config ds_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ds_out_wrap_target, offset + ds_out_wrap);
    return c;
}
#endif
